# Generated by Django 5.2 on 2026-05-24 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=200, verbose_name="Адрес пункта выдачи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт выдачи",
                "verbose_name_plural": "Пункты выдачи",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Артикул"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                (
                    "unit",
                    models.CharField(
                        default="шт.", max_length=100, verbose_name="Единица измерения"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(max_length=100, verbose_name="Поставщик"),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=100, verbose_name="Производитель"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("male", "Мужской парфюм"),
                            ("female", "Женский парфюм"),
                        ],
                        max_length=100,
                        verbose_name="Категория товара",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        default=0, verbose_name="Действующая скидка (%)"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="Количество на складе")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание товара"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Изображение товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Номер заказа"
                    ),
                ),
                ("order_date", models.DateField(verbose_name="Дата заказа")),
                ("delivery_date", models.DateField(verbose_name="Дата доставки")),
                ("pickup_code", models.IntegerField(verbose_name="Код для получения")),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "Новый"), ("completed", "Завершён")],
                        default="new",
                        max_length=100,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "pickup_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.pickuppoint",
                        verbose_name="Пункт выдачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказов",
                "unique_together": {("order", "product")},
            },
        ),
    ]
