# Generated by Django 5.2 on 2026-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_product_options_product_volume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                default="Флакон", max_length=100, verbose_name="Единица измерения"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="volume",
            field=models.CharField(
                choices=[("small", "50 мл."), ("large", "100 мл.")],
                max_length=50,
                verbose_name="Объем (мл.)",
            ),
        ),
    ]
